### ISSUE TITLE
The path of ``sysctl.h``  should be fixed in some Linux

### ISSUE THREAD

**Issue by shirayu** [ku-nlp/jumanpp#100]
For the build in Alpine Linux, the path of ``sysctl.h``  should be fixed in the following way.

```
sed -i 's|#include <sys/sysctl.h>|#include <linux/sysctl.h>|' src/util/assert.cc
```

**Comment by eiennohito** [comment]
The location should be checked by CMake I believe.

**Comment by eiennohito** [comment]
Ok, `#include <linux/sysctl.h>` brings the linux syscall.
https://linux.die.net/man/2/sysctl
And it is deprecated, so this is not a solution.

<sys/sysctl.h> should be a C library thing.
