### ISSUE TITLE
No output just "Model file was not specified" 

### ISSUE THREAD

**Issue by kdl-albert** [ku-nlp/jumanpp#102]
```
jumanpp-2.0.0-rc2/bld$ echo "テスト" | jumanpp
Model file was not specified
```

Version確認
```
umanpp --version
Juman++ Version: 2.0.0-dev
```
環境：
macOS,centOS7

**Comment by eiennohito** [comment]
I believe that you have built git version (2.0.0-dev is a version if you just download a tar.gz file without model).
It does not provide trained models.

Please download and build package that includes a trained model.
It is impossible to do any analysis without one.
The download should be ~500mb.

**Comment by CLRafaelR** [comment]
@eiennohito 

Is there any way to get a trained model from other sources than Juman++ when we install the git version of Juman++? If possible, do you have any suggestion for the model compatible with the git version of Juman++?

**Comment by eiennohito** [comment]
I agree that we certainly need to do something about providing fresh models. The current git version should (If I am not forgetting anything) work with -rc3 model, I want to do a couple of last breaking changes, fix the model format for the time being and release a non-rc version in couple next months.

**Comment by eiennohito** [comment]
@CLRafaelR if the -rc3 model does not work, please leave a comment, I will provide a model that works with the last git version.

**Comment by CLRafaelR** [comment]
Sorry but I'm too new to do this kind of things, so I'm unsure where "-rc3 model" is located and which directory I should put it in...

**Comment by CLRafaelR** [comment]
By the way, I successfully installed the released version (i.e. non-git ver.) of [v2.0.0-rc3](https://github.com/ku-nlp/jumanpp/releases/tag/v2.0.0-rc3) as well as the latest git ver., and I'm able to use Juman++ now.

**Comment by eiennohito** [comment]
It is possible to put the model folder from the released package into git directory; this will enable installing the git version with the model. Otherwise, you can just pass the path to the model configuration file with `--config=/path/to/installed/model/jumandic.conf`. Juman++ checks if the model is compatible and shows an error message in the case the model is incompatible.

**Comment by CLRafaelR** [comment]
Is it `jumandic.conf`, or `jumandic.jppmdl`? It seems that the git version is only missing `jumandic.jppmdl` and I suspect this should be the model...?

**Comment by eiennohito** [comment]
Thing in git is a configuration file template (after installing the model path is replaced by the correct path to the model).
