### ISSUE TITLE
--specifics defaults to top 0 candidates, outputting nothing

### ISSUE THREAD

**Issue by kouohhashi** [ku-nlp/jumanpp#109]
I'm trying Jumanpp 2.0.0-rc2.
But **_--specifics_** option is not working for me.

```
$ echo "大阪夏の陣で死亡した" | jumanpp --specifics
# MA-SCORE	
EOS
```

My version:
```
$ jumanpp -v
Juman++ Version: 2.0.0-rc2 / Dictionary: 20180202-2cca748 / LM: K:20180217-6c28641 L:20180221-fd8a4b63 F:20171214-9d125cb
```
I followed the install instruction of the github page.
If there was something I needed to do at installing, please let me know.
My OS: Ubuntu 16.04

Thanks in advance.

**Comment by eiennohito** [comment]
You need to call it as `echo "大阪夏の陣で死亡した" | jumanpp --specifics 1`, specifying how many items you want.

It seems that by default it uses 0, providing you with top 0 outputs 🤣
This is a very weird behavior, so please don't close this issue.
We need to default to beam-width, I think.

**Comment by kouohhashi** [comment]
Thanks!

**Comment by eiennohito** [comment]
This is a bug and I want to fix it, please don't close the issue.

**Comment by kouohhashi** [comment]
Oh sorry about that...
