### ISSUE TITLE
'pthread.h': No such file or directory

### ISSUE THREAD

**Issue by tanaken9440** [ku-nlp/jumanpp#110]
I built in the following environment, but an error occurred.
Please point out where in the procedure there is a mistake.

environment：
MSVC 2017 Community
Windows 7 (32bit)
CMake 3.14.0-rc1
jumanpp-2.0.0-rc2

command:
\jumanpp-2.0.0-rc2>mkdir build
\jumanpp-2.0.0-rc2>cd build
\jumanpp-2.0.0-rc2\build>cmake -G "Visual Studio 15 2017 Win64" ..
\jumanpp-2.0.0-rc2\build>cmake --build . --config Release

CMakeError.log:
\jumanpp-2.0.0-rc2\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [\jumanpp-2.0.0-rc2\build\CMakeFiles\CMakeTmp\cmTC_180a4.vcxproj]

**Comment by eiennohito** [comment]
I don't have a workable Windows environment right now and can't test your issue unfortunately, but it should not require `pthreads.h` on Windows.

**Comment by DoumanAsh** [comment]
I think this is harmless error due to how cmake threads library linking works.
It seems it tries to determine availability of `pthreads` using the header.
The error will not prevent you from building juman

**Comment by ColbertBrave** [comment]
pthread.h is a POSIX interface for UNIX/Linux

**Comment by eiennohito** [comment]
Juman++ is buildable both with recent MSVC and MSYS/MinGW64 environments. Closing this issue.

**Comment by eiennohito** [comment]
MSVC build is done by CI as well and passes without problems.
