### ISSUE TITLE
Without Web.dic  is possible ??

### ISSUE THREAD

**Issue by kento1109** [ku-nlp/jumanpp#119]
Thanks for building a great tool.
I do not want to contain Web.dic since the dictionary is not appropriate for my domain.
is it possible ??

**Comment by eiennohito** [comment]
We will open the sources for Jumandic and building the Jumanpp model soon. Using that you would be able to mix and match individual dictionaries.
The caveat is that you need to have the texts for the Kyoto Corpus (Mainichi Shinbun 1995 CD) , which we unfortunately can not distribute, for building the model.
