### ISSUE TITLE
モデルの学習について

### ISSUE THREAD

**Issue by Yoshi-smith** [ku-nlp/jumanpp#126]
V2のモデルファイル「jumandic.jppmdl」を学習させたいと考えているのですがどのような手順で学習させればよいのでしょうか？

**Comment by eiennohito** [comment]
遅くなってすみません。
京大コーパスの元テキストにアクセスありますか？ (http://nlp.ist.i.kyoto-u.ac.jp/?%E4%BA%AC%E9%83%BD%E5%A4%A7%E5%AD%A6%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%82%B3%E3%83%BC%E3%83%91%E3%82%B9)

**Comment by sy-ft-gh** [comment]
京大コーパスにはアクセスできます。
こちらはコーパスそのものとアノテーション方法が記載されている認識です。

jumanppの解析結果からJumanDICを利用し学習しているのではと考えているのですが、別途辞書情報を追加しコーパスを元にモデルを構築したいと考えております。

**Comment by Yoshi-smith** [comment]
京大コーパスにはアクセスできます。こちらコーパスのGitアノテーション方法が記載されている認識です。

jumanppの解析結果からJumanDICを利用し学習しているのではと考えているのですが、別途辞書を追加しコーパスを元にモデルを構築したいと考えております。

**Comment by eiennohito** [comment]
京大コーパスは元テキストが公開されていません。毎日新聞社から購入する必要があります。
githubのrepoとコーパスのホームページでは、アノテーションのデータしか載っていません。
が、学習には元のデータ＋アノテーションは両方必要です。

JumanDICは人の手で管理されている形態素解析辞書です（自動の部分もありますけど、基礎の単語は人で管理されています）。別の辞書を追加してモデルの再学習は全然可能ですが、問題はもともとのJumanDICやコーパスの単語分割基準と新しく追加する辞書の分割基準が異なれば、新しく追加した単語は解析のTop1で出ません。

**Comment by Yoshi-smith** [comment]
現在実施しようとしている取り組みは、辞書を元に形態素解析の結果を加工しようと考えておりJumanppの解析結果から大きく変えない予定です。jumanppの解析結果から人手やツールで加工し学習用のアノテーションを得ようと考えています。
学習用の元のデータとしては毎日新聞とは異なりますが、新聞記事に近い別ソースのニュース記事を用いようと考えております。そのため多くの加工を必要としない前提なのですが、学習方法が分からなかったので投稿させて頂いた次第です。

**Comment by eiennohito** [comment]
基本的に内部でモデルの学習をmakefileで行っています。
辞書の公開版でも簡単に使えるように手を加えたかったですが、作業が滞っています。
動かないmakefileは　https://gist.github.com/eiennohito/28e796acf2977700c42c56f475326509 です。京大コーパスの取得部分を修正する必要があります。
また、生のRNNモデルが必要で、http://lotus.kuee.kyoto-u.ac.jp/~arseny/jumanpp-rnn-raw.tar.bz2 は公開モデルと論文の実験で使われているものです。解凍後10m-unk.basep-96-40m-b5-retrainと10m-unk.basep-96-40m-b5-retrain.nnetの2つのファイルが出てくるはずです。

makefileの修正後、`RNN_MODEL_PATH=/path/to/10m-unk.basep-96-40m-b5-retrain make -f Jumanpp.train.makefile rnn` でモデルの学習はできます。

**Comment by Yoshi-smith** [comment]
jumanppとJumanDicのGitを確認したのですがRNN_MODEL_PATHについての記載が確認できませんでした。
makefileについてはjumanppのmakefileでしょうか？

**Comment by eiennohito** [comment]
お待たせしました。
モデルを学習するためのスクリプト集を公開しました
https://github.com/ku-nlp/jumanpp-jumandic

**Comment by sy-ft-gh** [comment]
ありがとうございます。

実施してみます。
