### ISSUE TITLE
Error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zhuobinggang** [ku-nlp/jumanpp#127]
Please try this:

```
echo この間講釈好きの松本の叔父から、詩と哲学の区別を聞かされて以来は、恐れない女と 恐れる男というと、たちまち自分に縁の遠い詩と哲学を想おもい出す | jumanpp
```

Just output: `Segmentation fault (core dumped)`

jumanpp version: JUMAN++ 1.02

**Comment by zhuobinggang** [comment]
And this:
```
echo ただ御礼だけ申し述べておきます | jumanpp
```

**Comment by eiennohito** [comment]
Juman++ v1 is not supported and will not recieve any new updates.
V2 works with your examples.

**Comment by zhuobinggang** [comment]
OK I got it, I will try v2, thank you
