### ISSUE TITLE
Output format is difficult to parse

### ISSUE THREAD

**Issue by meokz** [ku-nlp/jumanpp#128]
jumanppの結果をプログラミング言語を用いてパースする際、以下のようなパースが困難なケースに遭遇しました。(顔文字の中にスペースが入っており、区切りを意味するスペースと混在する)

```
こんにちは(^ ^)
こんにちは こんにちは こんにちは 感動詞 12 * 0 * 0 * 0 "代表表記:こんにちは/こんにちは"
(^ ^) (^ ^) (^ ^) 特殊 1 記号 5 * 0 * 0 "代表表記:顔文字/顔文字 顔文字"
```

これをうまくパースするための正規表現等の手法はありますか？
また、他のプログラミング言語でパースしやすくするための、出力形式のオプション等は存在しますか？

**Comment by eiennohito** [comment]
JUMAN出力形式（デフォルトの出力形式）は基本的に半角文字(特に空白、と `"` )に対応していません。
もし解析結果だけを取り出したければ、Lattice形式(`-s 1`)を使ったほうがいいです。
その形式はタブ区切りになりますが、入力のタブが`\t`に変換されます。

書きかけのドキュメント: https://github.com/ku-nlp/jumanpp/blob/master/docs/output.md

さらに、ProtobufがインストールされているシステムをJuman＋＋コンパイルすると、Protobuf出力形式も使えるようになります。
もしすでにほかのところでProtobufを使っていればこのやり方が一番楽で、そして出力の解析に一切曖昧性がありません。
https://github.com/ku-nlp/jumanpp/blob/master/src/jumandic/proto/juman.proto
使用例はこのレポにありませんけど

**Comment by eiennohito** [comment]
I'm closing this issue. If you have any comments, please reopen it.
