### ISSUE TITLE
Strange output, compiled from master

### ISSUE THREAD

**Issue by Pizzacus** [ku-nlp/jumanpp#142]
Hi!

I compiled Juman from the latest source on the `master`, and tried the "Quick Start" example, but I'm getting a strange result.

```bash
$ echo "魅力がたっぷりと詰まっている" | jumanpp
魅力 みりょく 魅力 名詞 6 普通名詞 1 * 0 * 0 "代表表記:魅力/みりょく カテゴリ:抽象物"
が が がる 接尾辞 14 動詞性接尾辞 7 子音動詞ラ行 10 語幹 1 "代表表記:がる/がる"
た た たる 動詞 2 * 0 子音動詞ラ行 10 語幹 1 "代表表記:足る/たる 自他動詞:他:足す/たす"
っ っ う 接尾辞 14 動詞性接尾辞 7 子音動詞ワ行 12 タ接連用形 9 "代表表記:う/う"
ぷ ぷ ぷ 未定義語 15 その他 1 * 0 * 0 "未知語:ひらがな 品詞推定:名詞"
り り る 接尾辞 14 動詞性接尾辞 7 子音動詞ラ行 10 基本連用形 8 "代表表記:る/る"
と と とぐ 動詞 2 * 0 子音動詞ガ行 4 語幹 1 "代表表記:研ぐ/とぐ ドメイン:料理・食事"
詰 なじ 詰る 動詞 2 * 0 子音動詞ラ行 10 語幹 1 "代表表記:詰る/なじる"
ま ま ま 接頭辞 13 名詞接頭辞 1 * 0 * 0 "代表表記:真/ま 内容語"
っ っ う 接尾辞 14 動詞性接尾辞 7 子音動詞ワ行 12 タ接連用形 9 "代表表記:う/う"
て て てる 動詞 2 * 0 子音動詞ラ行 10 語幹 1 "代表表記:照る/てる 自他動詞:他:照らす/てらす"
い い いる 接尾辞 14 動詞性接尾辞 7 母音動詞 1 未然形 3 "代表表記:いる/いる"
る る る 接尾辞 14 動詞性接尾辞 7 子音動詞ラ行 10 基本形 2 "代表表記:る/る"
```

I used the pretrained model from the `2.0.0-rc3` release. I moved the `model/` folder from that release to the root of the project before running cmake. I followed the installation instructions (I don't know C++, so I hope I'm doing it right). 

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
sudo make install -j5
```

The only other thing I did was changing the libeigen URL in `libs/CMakeLists.txt`, since [they are apparently having some problems right now](https://gitlab.com/libeigen/eigen/-/issues/2336), to [this fork](https://gitlab.com/cantonios/eigen).

I am on Manjaro and everything should be up to date.

Let me know if you have any ideas. Thanks in advance!

**Comment by eiennohito** [comment]
The commit https://github.com/ku-nlp/jumanpp/commit/95722f8ddbfcf42278c7b8f1239d612ebac714f1 has changed the feature hashing function, which makes it to produce nonsense with the models created by non-matching versions. Versions before it will work with -rc3 models, versions after it need a newer model.

I probably need to break the model compatibility.
For the time being, here is a model that should work: https://github.com/ku-nlp/jumanpp-jumandic/releases/download/2020.08.12/jumandic-rnn.model.tar.xz

**Comment by Pizzacus** [comment]
Just had time to test, and it works! Thank you so much :pray: 

```bash
echo "魅力がたっぷりと詰まっている" | jumanpp
魅力 みりょく 魅力 名詞 6 普通名詞 1 * 0 * 0 "代表表記:魅力/みりょく カテゴリ:抽象物"
が が が 助詞 9 格助詞 1 * 0 * 0 "代表表記:が/が"
たっぷり たっぷり たっぷりだ 形容詞 3 * 0 ナノ形容詞 22 語幹 1 "代表表記:たっぷりだ/たっぷりだ"
と と と 助詞 9 格助詞 1 * 0 * 0 "代表表記:と/と"
詰まって つまって 詰まる 動詞 2 * 0 子音動詞ラ行 10 タ系連用テ形 14 "代表表記:詰まる/つまる ドメイン:料理・食事 自他動詞:他:詰める/つめる"
いる いる いる 接尾辞 14 動詞性接尾辞 7 母音動詞 1 基本形 2 "代表表記:いる/いる"
EOS
```
