### ISSUE TITLE
[Question] How do I integrate this into the godot game engine.

### ISSUE THREAD

**Issue by hidemat** [ku-nlp/jumanpp#146]
Hello. The godot game engine is an open source cross-platform project for making games. I want to add morphological analysis in japanese for a game I'm working on. 

https://github.com/godotengine/godot

Since, godot is open source I can effectively integrate external libraries into it, either by adding them directly to source or creating c++ plugins. I know how to do this. However, as far as trying to integrate Jumanpp into godot, I don't know where to start, as apparently I need to build it with cmake?

Is there a way to use jumanpp internally in code without building it with cmake?

**Comment by eiennohito** [comment]
No, unfortunately the only way to use Juman++ currently is to use CMake build system. Also, Juman++ does not support dynamic linking at the moment, you need to statically link it into your executable.

**Comment by hidemat** [comment]
I see. Thanks for the clarification.
