### ISSUE TITLE
What kind of preprocessing is being done?

### ISSUE THREAD

**Issue by tealgreen0503** [ku-nlp/jumanpp#153]
During morphological analysis, it seems that certain preprocessing steps are taken. For instance, half-width spaces are converted to full-width spaces, and line breaks are eliminated.

I'm using [rhoknp](https://github.com/ku-nlp/rhoknp) for the analysis.

```python
import rhoknp
juman = rhoknp.Jumanpp()
text = " これは半角スペースです。"
print([morpheme.surf for morpheme in juman.apply_to_sentence(text).morphemes])
# ['\u3000', 'これ', 'は', '半角', 'スペース', 'です', '。']
text = "\nこれは改行です。"
print([morpheme.surf for morpheme in juman.apply_to_sentence(text).morphemes])
# ['これ', 'は', '改行', 'です', '。']
```

What other kinds of preprocessing might be done?

**Comment by eiennohito** [comment]
jumanpp does not perform any preprocessing on the input, it analysis input data as at is. If you are OK with the answer please close the issue.
