### ISSUE TITLE
Do you plan to release a new version of JUMAN++?

### ISSUE THREAD

**Issue by tealgreen0503** [ku-nlp/jumanpp#155]
Are there plans to release an updated version of JUMAN++? The most recent version, 2.0.0-rc3, seems to be from 2019. Specifically, the update from #151 is necessary for newer Linux versions, such as Ubuntu 22.04 and Debian Bookworm. I would greatly appreciate a new release, perhaps 2.0.0-rc4 or 2.0.0.

**Comment by eiennohito** [comment]
Certainly I should, thanks for the reminder.

**Comment by eiennohito** [comment]
Published v2.0.0-rc4 with a working model inside for the time being. Please report if you have any problems. Builds without problem on Arch and Ubuntu 22.04
