### ISSUE TITLE
There are some duplicated entries

### ISSUE THREAD

**Issue by shirayu** [ku-nlp/jumanpp#5]
For example, `すげえ` has duplicated entries.

```
$ jumanpp
すげえ
すげえ すげえ すごい 形容詞 3 * 0 イ形容詞アウオ段 18 エ基本形 23 "代表表記:凄い/すごい"
@ すげえ すげえ すごい 形容詞 3 * 0 イ形容詞アウオ段 18 エ基本形 23 "代表表記:凄い/すごい"
EOS
```

I thought it might be related to `エ基本形`, but there are no duplicated entries for `ありがてえ`.

```
$ jumanpp
ありがてえ
ありがてえ ありがてえ ありがたい 形容詞 3 * 0 イ形容詞アウオ段 18 エ基本形 23 "代表表記:有り難い/ありがたい"
```

**Comment by eiennohito** [comment]
Nice find! I have seen duplicated nodes somewhere else.

It seems that there are lattice nodes which have exactly same content, but different ids.

**Comment by eiennohito** [comment]
Can't reproduce in v2, so closing.
