### ISSUE TITLE
Setting up Travis

### ISSUE THREAD

**Issue by DoumanAsh** [ku-nlp/jumanpp#63]
Considering that i'm working on porting current code to MSVC, it might be good idea to ensure that nothing will get broken by setting up Travis to build and test existing code.

If you'd like I can prepare travis config myself (in future I'd like to setup AppVeyor to verify windows builds).
Since I cannot build myself yet I cannot know how long it might take, but eventually some sorta CI might be required to ensure that codebase remains portable

**Comment by eiennohito** [comment]
I'll try to setup linux build today. I'm using a jenkins instance internally, actually, but I won't expose it to the internet, it is lab-only.

**Comment by eiennohito** [comment]
I will try to use gitflow for my work as well, trying not push a lot of stuff into master.
