### ISSUE TITLE
Revive --autoN and --autoNbase options that existed in v1

### ISSUE THREAD

**Issue by dkawahara** [ku-nlp/jumanpp#67]
I want to use the --autoN and --autoNbase options to use some scripts that worked with v1. The format can be "--auto-nbest=<min>:<increment>:<max>".

**Comment by eiennohito** [comment]
Use max parameter as the local/global beam parameters. Calculate only top-n for the output.

**Comment by eiennohito** [comment]
Design: 
--auto-nbest=<min>:<increment>:<max>

Where min is a minimum number of different output paths, max is the maximum, and increment is the number of codepoints in a input sentence which increments the number of paths by 1.

**Comment by eiennohito** [comment]
I changed the spec, so the beam width would apply only to local and left global beams.
Modifying right global beam is not productive because it does not cause problems with the sentence length.
