### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by yosato** [ku-nlp/jumanpp#89]
Just followed the instruction, build seems to have finished (very quickly, maybe that's what cmake does?) but make install spits out the following errors (rather just the beginning, as the message is too long)

Any advice? My env is a mac, a little old El Capitan.

[  3%] Built target jpp_test_catch_main_lib
[  3%] Building CXX object src/util/CMakeFiles/jpp_util.dir/mmap.cc.o
In file included from /Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/mmap.cc:9:
In file included from /Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/mmap.h:12:
In file included from /Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/status.hpp:8:
/Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/string_piece.h:109:43: error:
      constexpr function never produces a constant expression
      [-Winvalid-constexpr]
  JPP_ALWAYS_INLINE constexpr StringPiece slice(ptrdiff_t from,
                                          ^
/Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/string_piece.h:114:22: note:
      non-constexpr function 'min<const char *>' cannot be used in a constant
      expression
    auto begin_new = std::min(begin() + from, end());
                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2544:1: note:
      declared here
min(const _Tp& __a, const _Tp& __b)
^
In file included from /Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/mmap.cc:9:
In file included from /Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/mmap.h:12:
In file included from /Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/status.hpp:8:
/Users/yosato/Downloads/jumanpp-2.0.0-rc2/src/util/string_piece.h:119:43: error:
      constexpr function never produces a constant expression
      [-Winvalid-constexpr]

**Comment by eiennohito** [comment]
I think that your XCode (clang) is pretty old, and it probably survived several upgrades of OS X without updates. I wonder what is the version.

**Comment by eiennohito** [comment]
At least the version 7.3.0 is known to work.

**Comment by yosato** [comment]
thanks for your quick reply, but I did do the upgrade due to some other error earlier. So the Xcode is very much tiptop, like 9.3. But i don't know what 'clang' version is.

**Comment by eiennohito** [comment]
You can check it by typing `clang --version` in the terminal. Another option would be is to try to install llvm/gcc from Homebrew or whatever and use it to build Juman++.
Just pass it to cmake like `CXX=g++-7 cmake ...` (for gcc 7).

I don't think that 9.3 can even be installed on El Capitan. It works only on High Sierra and above [by Apple docs at least](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html) and I remember some problems I had myself when trying to install the latest version of XCode on older OSX.

**Comment by yosato** [comment]
ok, in fact xcodebuild -version says 6.1. The mac updater simply froze, so I manually downloaded 9.3, and was led to think it was installed because there was no complaint in the process...  Now tryng your alternative.

**Comment by eiennohito** [comment]
Try https://download.developer.apple.com/Developer_Tools/Xcode_7.3.1/Xcode_7.3.1.dmg

**Comment by eiennohito** [comment]
Could you please a post the full log to a gist when you try to build with g++-8.
Both of `cmake` and `make` (please do run `make VERBOSE=1`). And run the build in an empty directory.

**Comment by yosato** [comment]
with an empty dir, i now get this:
 
 The C++ compiler

    "/usr/local/bin/g++-8" is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/yosato/Downloads/jumanpp-2.0.0-rc2/bld2/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_075f5/fast"
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_075f5.dir/build.make CMakeFiles/cmTC_075f5.dir/build
    Building CXX object CMakeFiles/cmTC_075f5.dir/testCXXCompiler.cxx.o
    /usr/local/bin/g++-8     -o CMakeFiles/cmTC_075f5.dir/testCXXCompiler.cxx.o -c /Users/yosato/Downloads/jumanpp-2.0.0-rc2/bld2/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    FATAL:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
    make[1]: *** [CMakeFiles/cmTC_075f5.dir/testCXXCompiler.cxx.o] Error 1
    make: *** [cmTC_075f5/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Comment by eiennohito** [comment]
Does g++-8 even work with a simple hello world program for you?
By the log output it seems there is a compatibility? problem with a toolchain (namely assembler does not understand gcc flags).

**Comment by eiennohito** [comment]
I have no problems with building using g++-8 locally.

The configuration command is `CXX=g++-8 cmake .. -DCMAKE_BUILD_TYPE=Release -DJPP_USE_PROTOBUF=OFF`

**Comment by yosato** [comment]
Hi, sorry for a bit of silence. I finally got round to do this, and to cut a long story short, I've managed to install it by upgrading xcode to 7.3.1. No other way worked. Might mention the fact that I also need to do 'sudo make', which probably is not recommended. Furthermore, though I wanted to install in a different directory than /usr/local, somehow it returned a permission denied error (even with sudo).

**Comment by eiennohito** [comment]
When using CMake-based builds (it's not specific to Juman++) you can customize installation prefix by using `-DCMAKE_INSTALL_PREFIX=<prefix>` as written in the Readme. The default is /usr/local though.

g++ should definitely use  the bounded C++ library instead of the system one (which was causing installation problems). I wonder what went wrong. Nevertheless, thank you for the report. 

I will close this issue. Feel free to reopen (or create an another one) if you other problems.
